from django.urls import path
from .views import (
    InventoryBookCreateView,
    InventoryBookListView,
    InventoryBookDeleteView,
    ActivatedInventoryBookListView,
    ActivateInventoryBookView,
    ScanSoldTicketView,
    DashboardStatsView,
    TicketValuesView,
    MarkInventoryBookSoldView,
    MoveActivatedPackView,
    DailyReportListView,
    DailyReportUpdateView,
    EndShiftView,
    DailyReportBoxDetailListView,
    DailySalesView,
    TodayEndShiftStatusView,
    TodayReportView,
    DailyReportDownloadPDFView,
    LoginView,
    SignupView,
    CurrentUserView,
    DirectSaleInventoryBookView,
)

urlpatterns = [
    path('books/', InventoryBookListView.as_view(), name='inventory-book-list'),
    path('books/add/', InventoryBookCreateView.as_view(), name='inventory-book-add'),
    path('books/<int:pk>/', InventoryBookDeleteView.as_view(), name='inventory-book-delete'),
    # path('activated-packs/', ActivatedPackListView.as_view(), name='activated-pack-list'),
    # path('activated-packs/add/', ActivatePackCreateView.as_view(), name='activated-pack-add'),
    # path('activated-packs/<int:pk>/', ActivatedPackDeleteView.as_view(), name='activated-pack-delete'),
    path('activated-books/', ActivatedInventoryBookListView.as_view(), name='activated-book-list'),
    path('activated-books/activate/', ActivateInventoryBookView.as_view(), name='activated-book-activate'),
    path('tickets/scan/', ScanSoldTicketView.as_view(), name='scan-sold-ticket'),
    path('dashboard-stats/', DashboardStatsView.as_view(), name='dashboard-stats'),
    path('ticket-values/', TicketValuesView.as_view(), name='ticket-values'),
    path('daily-sales/', DailySalesView.as_view(), name='daily-sales'),
    path('inventory-books/<int:pk>/mark-sold/', MarkInventoryBookSoldView.as_view(), name='mark-inventory-book-sold'),
    path('activated-books/<int:pk>/move/', MoveActivatedPackView.as_view(), name='move-activated-pack'),
    path('reports/', DailyReportListView.as_view(), name='daily-report-list'),
    path('reports/<int:pk>/', DailyReportUpdateView.as_view(), name='daily-report-update'),
    path('end-shift/', EndShiftView.as_view(), name='end-shift'),
    path('reports/<int:pk>/box-details/', DailyReportBoxDetailListView.as_view(), name='report-box-details'),
    path('reports/today-status/', TodayEndShiftStatusView.as_view(), name='today-endshift-status'),
    path('reports/today/', TodayReportView.as_view(), name='today-report'),
    path('reports/<int:pk>/download/', DailyReportDownloadPDFView.as_view(), name='report-download-pdf'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('current-user/', CurrentUserView.as_view(), name='current-user'),
    path('inventory/<int:pk>/direct-sale/', DirectSaleInventoryBookView.as_view(), name='inventory-direct-sale'),

]