# Generated by Django 6.0.3 on 2026-04-02 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LotteryGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=4, unique=True)),
                ("ticket_count", models.PositiveIntegerField()),
                ("ticket_value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pack_id", models.CharField(max_length=20)),
                ("raw_barcode", models.CharField(max_length=100, unique=True)),
                ("total_tickets", models.PositiveIntegerField()),
                ("remaining_tickets", models.PositiveIntegerField()),
                ("ticket_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="inventory.lotterygame",
                    ),
                ),
            ],
            options={"unique_together": {("game", "pack_id")},},
        ),
    ]
