# Generated by Django 6.0.3 on 2026-04-13 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lottery_games/"
                    ),
                ),
                ("ticket_count", models.PositiveIntegerField()),
                ("ticket_value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "instant_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "instant_cashes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "online_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "online_cashes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "online_cancels",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "unique_together": {("user", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="InventoryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pack_id", models.CharField(max_length=20)),
                ("raw_barcode", models.CharField(max_length=100)),
                ("is_activated", models.BooleanField(default=False)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_returned", models.BooleanField(default=False)),
                ("total_tickets", models.PositiveIntegerField()),
                ("ticket_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="inventory.lotterygame",
                    ),
                ),
            ],
            options={"unique_together": {("user", "game", "pack_id")},},
        ),
        migrations.CreateModel(
            name="DailyReportBoxDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("box_num", models.CharField(max_length=20)),
                ("lottery_name", models.CharField(max_length=200)),
                ("game_num", models.CharField(max_length=20)),
                ("pack_num", models.CharField(max_length=20)),
                ("start_num", models.PositiveIntegerField(default=0)),
                ("current_num", models.PositiveIntegerField(default=0)),
                (
                    "ticket_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("closing_status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_details",
                        to="inventory.dailyreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_report_box_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_report_box_details",
                        to="inventory.inventorybook",
                    ),
                ),
            ],
            options={"ordering": ["box_num", "id"],},
        ),
        migrations.CreateModel(
            name="SoldTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.PositiveIntegerField()),
                ("delta_count", models.IntegerField(default=0)),
                ("is_reversal", models.BooleanField(default=False)),
                ("scanned_code", models.CharField(max_length=100)),
                ("sold_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_tickets",
                        to="inventory.inventorybook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-sold_at"],},
        ),
        migrations.CreateModel(
            name="ActivatedPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_num", models.CharField(max_length=20)),
                ("reverse_mode", models.BooleanField(default=False)),
                ("current_count", models.PositiveIntegerField(default=0)),
                ("last_ticket", models.PositiveIntegerField(default=0)),
                ("today_start", models.PositiveIntegerField(default=0)),
                ("tomorrow_start", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activated_packs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activated_packs",
                        to="inventory.inventorybook",
                    ),
                ),
            ],
            options={"unique_together": {("user", "box_num")},},
        ),
    ]
