# Generated by Django 6.0.3 on 2026-04-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotterygame",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lottery_games/"),
        ),
        migrations.AddField(
            model_name="lotterygame",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
