# Generated by Django 6.0.3 on 2026-04-03 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_lotterygame_image_lotterygame_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivatedPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_num", models.CharField(max_length=20)),
                ("reverse_mode", models.BooleanField(default=False)),
                ("current_num", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activated_packs",
                        to="inventory.inventorybook",
                    ),
                ),
            ],
            options={"unique_together": {("box_num",)},},
        ),
    ]
