# Generated by Django 4.2.30 on 2026-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_activatedpack_id_alter_dailyreport_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='JackpotValue',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('game_name', models.CharField(max_length=50, unique=True)),
                        ('amount_text', models.CharField(max_length=50)),
                        ('amount_number', models.BigIntegerField(blank=True, null=True)),
                        ('source_url', models.URLField(blank=True, null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                ),
            ],
        ),
    ]
