# Generated by Django 6.0.3 on 2026-04-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_activatedpack"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybook",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
