# Generated by Django 4.2.26 on 2026-05-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_jackpotvalue_alter_activatedpack_id_and_more'),
        ('inventory', '0003_jackpotvalue'),
    ]

    operations = [
    ]
