# Generated by Django 6.0.3 on 2026-04-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventorybook_is_activated"),
    ]

    operations = [
        migrations.AddField(
            model_name="activatedpack",
            name="current_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activatedpack",
            name="last_scanned_ticket",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name="SoldTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.PositiveIntegerField()),
                ("scanned_code", models.CharField(max_length=100, unique=True)),
                ("sold_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_tickets",
                        to="inventory.inventorybook",
                    ),
                ),
            ],
            options={"unique_together": {("inventory_book", "ticket_number")},},
        ),
    ]
