# Generated by Django 6.0.3 on 2026-04-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_activatedpack_current_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="activatedpack", name="current_num",),
        migrations.RemoveField(model_name="activatedpack", name="last_scanned_ticket",),
        migrations.RemoveField(model_name="inventorybook", name="remaining_tickets",),
        migrations.AddField(
            model_name="activatedpack",
            name="last_ticket",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
