# Generated by Django 4.2.26 on 2026-07-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_storeowner_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('shift_number', models.PositiveIntegerField()),
                ('shift_started_at', models.DateTimeField(blank=True, null=True)),
                ('shift_ended_at', models.DateTimeField(blank=True, null=True)),
                ('instant_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('instant_cashes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('online_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('online_cashes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('online_cancels', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-shift_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.PositiveIntegerField(default=1)),
                ('instant_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftReportBoxDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('shift_number', models.PositiveIntegerField()),
                ('box_num', models.CharField(max_length=20)),
                ('lottery_name', models.CharField(max_length=200)),
                ('game_num', models.CharField(max_length=20)),
                ('pack_num', models.CharField(max_length=20)),
                ('start_num', models.PositiveIntegerField(default=0)),
                ('current_num', models.PositiveIntegerField(default=0)),
                ('ticket_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_report_box_details', to='inventory.inventorybook')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_details', to='inventory.shiftreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_report_box_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['box_num', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.UniqueConstraint(fields=('user', 'report_date', 'shift_number'), name='unique_user_date_shift_number'),
        ),
    ]
