# Generated by Django 6.0.3 on 2026-04-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_activatedpack_current_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldticket",
            name="delta_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="soldticket",
            name="is_reversal",
            field=models.BooleanField(default=False),
        ),
    ]
