# Generated by Django 4.2.26 on 2026-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_shiftreport_shiftstate_shiftreportboxdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybook',
            name='activated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
