# Generated by Django 6.0.3 on 2026-04-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_soldticket_delta_count_soldticket_is_reversal"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybook",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
