# Generated by Django 6.0.3 on 2026-04-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_inventorybook_is_sold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soldticket", options={"ordering": ["-sold_at"]},
        ),
        migrations.AlterUniqueTogether(name="soldticket", unique_together=set(),),
    ]
