# Generated by Django 4.2.30 on 2026-07-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorybook_activated_at_store_manager_pin_hash'),
        ('inventory', '0009_alter_activatedpack_id_alter_dailyreport_id_and_more'),
    ]

    operations = [
    ]
