# Generated by Django 6.0.3 on 2026-04-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_soldticket_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soldticket',
            unique_together=set(),
        ),
    ]
