# Generated by Django 6.0.3 on 2026-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_soldticket_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldticket",
            name="scanned_code",
            field=models.CharField(max_length=100),
        ),
    ]
