# Generated by Django 6.0.3 on 2026-04-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_soldticket_scanned_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(unique=True)),
                (
                    "instant_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "instant_cashes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "online_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "online_cashes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "online_cancels",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-report_date"],},
        ),
    ]
