# Generated by Django 6.0.3 on 2026-04-12 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_dailyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="activatedpack",
            name="today_start",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activatedpack",
            name="tomorrow_start",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DailyReportBoxDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("box_num", models.CharField(max_length=20)),
                ("lottery_name", models.CharField(max_length=200)),
                ("game_num", models.CharField(max_length=20)),
                ("pack_num", models.CharField(max_length=20)),
                ("start_num", models.PositiveIntegerField(default=0)),
                ("current_num", models.PositiveIntegerField(default=0)),
                (
                    "ticket_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("closing_status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_report_box_details",
                        to="inventory.inventorybook",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_details",
                        to="inventory.dailyreport",
                    ),
                ),
            ],
            options={"ordering": ["box_num", "id"],},
        ),
    ]
