# Generated by Django 6.0.3 on 2026-04-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_activatedpack_today_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybook",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
